// A curated (not exhaustive) directory of commonly-traded TW and US tickers,
// used only to power the buy-side autocomplete suggestions — every free
// data source that could have supplied a live, complete list (TWSE OpenAPI,
// SEC EDGAR, Yahoo Finance, NASDAQ) blocks direct browser fetches with no
// CORS headers, and this app has no backend to proxy one through. A ticker
// not in here still works fine: the field stays a normal free-text input,
// this just adds suggestions on top of it.
const TICKER_DIRECTORY = {
  TW: [
    { code: '0050', name: '元大台灣50' },
    { code: '0056', name: '元大高股息' },
    { code: '00878', name: '國泰永續高股息' },
    { code: '00919', name: '群益台灣精選高息' },
    { code: '00929', name: '復華台灣科技優息' },
    { code: '00939', name: '統一台灣高息動能' },
    { code: '00940', name: '元大台灣價值高息' },
    { code: '006208', name: '富邦台50' },
    { code: '00713', name: '元大台灣高息低波' },
    { code: '00757', name: '統一FANG+' },
    { code: '00830', name: '國泰費城半導體' },
    { code: '00733', name: '富邦臺灣中小' },
    { code: '00692', name: '富邦公司治理' },
    { code: '00850', name: '元大臺灣ESG永續' },
    { code: '00891', name: '中信關鍵半導體' },
    { code: '00892', name: '富邦台灣半導體' },
    { code: '006201', name: '元大富櫃50' },
    { code: '2330', name: '台積電' },
    { code: '2317', name: '鴻海' },
    { code: '2454', name: '聯發科' },
    { code: '2303', name: '聯電' },
    { code: '2382', name: '廣達' },
    { code: '2357', name: '華碩' },
    { code: '2395', name: '研華' },
    { code: '3008', name: '大立光' },
    { code: '2379', name: '瑞昱' },
    { code: '3034', name: '聯詠' },
    { code: '3711', name: '日月光投控' },
    { code: '2308', name: '台達電' },
    { code: '2327', name: '國巨' },
    { code: '2377', name: '微星' },
    { code: '2409', name: '友達' },
    { code: '3037', name: '欣興' },
    { code: '2408', name: '南亞科' },
    { code: '6446', name: '藥華藥' },
    { code: '4938', name: '和碩' },
    { code: '2412', name: '中華電' },
    { code: '3045', name: '台灣大' },
    { code: '4904', name: '遠傳' },
    { code: '2881', name: '富邦金' },
    { code: '2882', name: '國泰金' },
    { code: '2886', name: '兆豐金' },
    { code: '2891', name: '中信金' },
    { code: '2884', name: '玉山金' },
    { code: '2892', name: '第一金' },
    { code: '2880', name: '華南金' },
    { code: '2883', name: '開發金' },
    { code: '2887', name: '台新金' },
    { code: '5880', name: '合庫金' },
    { code: '2890', name: '永豐金' },
    { code: '2801', name: '彰銀' },
    { code: '2885', name: '元大金' },
    { code: '2888', name: '新光金' },
    { code: '6505', name: '台塑化' },
    { code: '1301', name: '台塑' },
    { code: '1303', name: '南亞' },
    { code: '1326', name: '台化' },
    { code: '1101', name: '台泥' },
    { code: '1102', name: '亞泥' },
    { code: '2002', name: '中鋼' },
    { code: '2201', name: '裕隆' },
    { code: '2207', name: '和泰車' },
    { code: '2603', name: '長榮' },
    { code: '2609', name: '陽明' },
    { code: '2615', name: '萬海' },
    { code: '2610', name: '華航' },
    { code: '2618', name: '長榮航' },
    { code: '2912', name: '統一超' },
    { code: '1216', name: '統一' },
    { code: '9914', name: '美利達' },
    { code: '9921', name: '巨大' },
    { code: '6488', name: '環球晶' },
    { code: '5269', name: '祥碩' },
    { code: '3529', name: '力旺' },
    { code: '3661', name: '世芯-KY' },
    { code: '6669', name: '緯穎' },
    { code: '2376', name: '技嘉' },
    { code: '2356', name: '英業達' },
    { code: '2360', name: '致茂' },
    { code: '3231', name: '緯創' },
    { code: '2352', name: '佳世達' },
    { code: '8046', name: '南電' },
    { code: '3406', name: '玉晶光' },
    { code: '2385', name: '群光' },
    { code: '4990', name: '華星光' },
    { code: '2449', name: '京元電子' },
    { code: '5347', name: '世界先進' },
    { code: '3443', name: '創意' },
    { code: '3105', name: '穩懋' },
    { code: '2481', name: '強茂' },
    { code: '1802', name: '台玻' },
    { code: '9945', name: '潤泰新' },
    { code: '9904', name: '寶成' },
    { code: '2915', name: '潤泰全' },
    { code: '5871', name: '中租-KY' },
    { code: '2867', name: '三商壽' },
    { code: '6547', name: '高端疫苗' },
    { code: '4128', name: '中天' },
    { code: '1795', name: '美時' },
    { code: '6180', name: '遊戲橘子' },
    { code: '3293', name: '鈊象' },
    { code: '8299', name: '群聯' },
    { code: '2049', name: '上銀' },
    { code: '4551', name: '智伸科' },
    { code: '6244', name: '茂迪' },
    { code: '3532', name: '台勝科' },
    { code: '3563', name: '牧德' },
  ],
  US: [
    { code: 'AAPL', name: 'Apple' },
    { code: 'MSFT', name: 'Microsoft' },
    { code: 'GOOGL', name: 'Alphabet (Class A)' },
    { code: 'GOOG', name: 'Alphabet (Class C)' },
    { code: 'AMZN', name: 'Amazon' },
    { code: 'META', name: 'Meta Platforms' },
    { code: 'NVDA', name: 'NVIDIA' },
    { code: 'TSLA', name: 'Tesla' },
    { code: 'AVGO', name: 'Broadcom' },
    { code: 'ORCL', name: 'Oracle' },
    { code: 'CRM', name: 'Salesforce' },
    { code: 'ADBE', name: 'Adobe' },
    { code: 'AMD', name: 'Advanced Micro Devices' },
    { code: 'INTC', name: 'Intel' },
    { code: 'QCOM', name: 'Qualcomm' },
    { code: 'TXN', name: 'Texas Instruments' },
    { code: 'IBM', name: 'International Business Machines' },
    { code: 'CSCO', name: 'Cisco Systems' },
    { code: 'NOW', name: 'ServiceNow' },
    { code: 'INTU', name: 'Intuit' },
    { code: 'AMAT', name: 'Applied Materials' },
    { code: 'MU', name: 'Micron Technology' },
    { code: 'LRCX', name: 'Lam Research' },
    { code: 'KLAC', name: 'KLA Corporation' },
    { code: 'PANW', name: 'Palo Alto Networks' },
    { code: 'SNOW', name: 'Snowflake' },
    { code: 'PLTR', name: 'Palantir Technologies' },
    { code: 'UBER', name: 'Uber Technologies' },
    { code: 'ABNB', name: 'Airbnb' },
    { code: 'SHOP', name: 'Shopify' },
    { code: 'SQ', name: 'Block (Square)' },
    { code: 'PYPL', name: 'PayPal' },
    { code: 'NFLX', name: 'Netflix' },
    { code: 'DIS', name: 'Walt Disney' },
    { code: 'CMCSA', name: 'Comcast' },
    { code: 'JPM', name: 'JPMorgan Chase' },
    { code: 'BAC', name: 'Bank of America' },
    { code: 'WFC', name: 'Wells Fargo' },
    { code: 'GS', name: 'Goldman Sachs' },
    { code: 'MS', name: 'Morgan Stanley' },
    { code: 'C', name: 'Citigroup' },
    { code: 'V', name: 'Visa' },
    { code: 'MA', name: 'Mastercard' },
    { code: 'AXP', name: 'American Express' },
    { code: 'BLK', name: 'BlackRock' },
    { code: 'SCHW', name: 'Charles Schwab' },
    { code: 'SPGI', name: 'S&P Global' },
    { code: 'BRK.B', name: 'Berkshire Hathaway (Class B)' },
    { code: 'JNJ', name: 'Johnson & Johnson' },
    { code: 'UNH', name: 'UnitedHealth Group' },
    { code: 'PFE', name: 'Pfizer' },
    { code: 'LLY', name: 'Eli Lilly' },
    { code: 'ABBV', name: 'AbbVie' },
    { code: 'MRK', name: 'Merck' },
    { code: 'TMO', name: 'Thermo Fisher Scientific' },
    { code: 'ABT', name: 'Abbott Laboratories' },
    { code: 'DHR', name: 'Danaher' },
    { code: 'BMY', name: 'Bristol-Myers Squibb' },
    { code: 'AMGN', name: 'Amgen' },
    { code: 'GILD', name: 'Gilead Sciences' },
    { code: 'CVS', name: 'CVS Health' },
    { code: 'MDT', name: 'Medtronic' },
    { code: 'ISRG', name: 'Intuitive Surgical' },
    { code: 'WMT', name: 'Walmart' },
    { code: 'PG', name: 'Procter & Gamble' },
    { code: 'KO', name: 'Coca-Cola' },
    { code: 'PEP', name: 'PepsiCo' },
    { code: 'COST', name: 'Costco Wholesale' },
    { code: 'MCD', name: "McDonald's" },
    { code: 'NKE', name: 'Nike' },
    { code: 'SBUX', name: 'Starbucks' },
    { code: 'TGT', name: 'Target' },
    { code: 'HD', name: 'Home Depot' },
    { code: 'LOW', name: "Lowe's" },
    { code: 'EL', name: 'Estée Lauder' },
    { code: 'CL', name: 'Colgate-Palmolive' },
    { code: 'KHC', name: 'Kraft Heinz' },
    { code: 'MDLZ', name: 'Mondelez International' },
    { code: 'XOM', name: 'Exxon Mobil' },
    { code: 'CVX', name: 'Chevron' },
    { code: 'BA', name: 'Boeing' },
    { code: 'CAT', name: 'Caterpillar' },
    { code: 'GE', name: 'General Electric' },
    { code: 'HON', name: 'Honeywell' },
    { code: 'UPS', name: 'United Parcel Service' },
    { code: 'FDX', name: 'FedEx' },
    { code: 'LMT', name: 'Lockheed Martin' },
    { code: 'RTX', name: 'RTX Corporation' },
    { code: 'DE', name: 'Deere & Company' },
    { code: 'MMM', name: '3M' },
    { code: 'UNP', name: 'Union Pacific' },
    { code: 'NOC', name: 'Northrop Grumman' },
    { code: 'COP', name: 'ConocoPhillips' },
    { code: 'SLB', name: 'Schlumberger' },
    { code: 'T', name: 'AT&T' },
    { code: 'VZ', name: 'Verizon Communications' },
    { code: 'TMUS', name: 'T-Mobile US' },
    { code: 'TSM', name: 'Taiwan Semiconductor Manufacturing (ADR)' },
    { code: 'ASML', name: 'ASML Holding' },
    { code: 'ARM', name: 'Arm Holdings' },
    { code: 'F', name: 'Ford Motor' },
    { code: 'GM', name: 'General Motors' },
    { code: 'RIVN', name: 'Rivian Automotive' },
    { code: 'LCID', name: 'Lucid Group' },
    { code: 'COIN', name: 'Coinbase Global' },
    { code: 'SOFI', name: 'SoFi Technologies' },
    { code: 'RBLX', name: 'Roblox' },
    { code: 'DASH', name: 'DoorDash' },
    { code: 'ZM', name: 'Zoom Video Communications' },
    { code: 'DOCU', name: 'DocuSign' },
    { code: 'CRWD', name: 'CrowdStrike Holdings' },
    { code: 'DDOG', name: 'Datadog' },
    { code: 'NET', name: 'Cloudflare' },
    { code: 'MDB', name: 'MongoDB' },
    { code: 'TEAM', name: 'Atlassian' },
    { code: 'WDAY', name: 'Workday' },
    { code: 'SPY', name: 'SPDR S&P 500 ETF Trust' },
    { code: 'VOO', name: 'Vanguard S&P 500 ETF' },
    { code: 'VTI', name: 'Vanguard Total Stock Market ETF' },
    { code: 'QQQ', name: 'Invesco QQQ Trust (Nasdaq 100)' },
    { code: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF' },
    { code: 'IWM', name: 'iShares Russell 2000 ETF' },
    { code: 'VEA', name: 'Vanguard FTSE Developed Markets ETF' },
    { code: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF' },
    { code: 'ARKK', name: 'ARK Innovation ETF' },
    { code: 'SCHD', name: 'Schwab US Dividend Equity ETF' },
    { code: 'VYM', name: 'Vanguard High Dividend Yield ETF' },
    { code: 'JEPI', name: 'JPMorgan Equity Premium Income ETF' },
    { code: 'XLK', name: 'Technology Select Sector SPDR Fund' },
    { code: 'XLF', name: 'Financial Select Sector SPDR Fund' },
    { code: 'XLE', name: 'Energy Select Sector SPDR Fund' },
    { code: 'XLV', name: 'Health Care Select Sector SPDR Fund' },
    { code: 'SOXX', name: 'iShares Semiconductor ETF' },
    { code: 'SMH', name: 'VanEck Semiconductor ETF' },
    { code: 'GLD', name: 'SPDR Gold Shares' },
    { code: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF' },
    { code: 'BND', name: 'Vanguard Total Bond Market ETF' },
    { code: 'VXUS', name: 'Vanguard Total International Stock ETF' },
  ],
};

window.TickerDirectory = TICKER_DIRECTORY;
