"""Regenerates app/js/holidays.js from the official Taiwan office calendars.

Run from the project root:  python tools/build_holidays.py

Inputs
  data/import/*年中華民國政府行政機關辦公日曆表.csv
      行政院人事行政總處's 「中華民國政府行政機關辦公日曆表」 from
      https://data.gov.tw/dataset/14718 — the plain format, NOT the
      「Google行事曆專用」 one. One row per day: 西元日期, 星期,
      是否放假 (0 work / 2 off), 備註 (the holiday's name, 補假, 補行上班).
      Older years are Big5, newer ones UTF-8; both are read.

Each year (the next year's calendar is usually published around June/July):
download that year's plain CSV into data/import/, run this script, commit
app/js/holidays.js.

Only the days a plain weekday rule gets wrong are kept: an off day that is
not a Saturday/Sunday, a working Saturday/Sunday (補行上班), and any day the
calendar names (a holiday falling on a weekend still gets its name shown).
"""
import csv
import datetime
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMPORT = ROOT / "data" / "import"
OUT = ROOT / "app" / "js" / "holidays.js"

# A calendar cell has room for about three characters; the full name still
# shows beside the selected day's date.
SHORT_NAMES = {
    "開國紀念日": "元旦",
    "農曆除夕": "除夕",
    "和平紀念日": "228",
    "兒童節及民族掃墓節": "兒童節",
    "孔子誕辰紀念日": "教師節",
    "孔子誕辰紀念日/教師節": "教師節",
    "臺灣光復暨金門古寧頭大捷紀念日": "光復節",
    "行憲紀念日": "行憲日",
    "補行上班": "補班",
    "調整放假": "調假",
}


def read_text(path):
    raw = path.read_bytes()
    for encoding in ("utf-8-sig", "cp950"):
        try:
            return raw.decode(encoding)
        except UnicodeDecodeError:
            continue
    raise ValueError(f"{path.name}: neither UTF-8 nor Big5")


def main():
    files = sorted(IMPORT.glob("*年中華民國政府行政機關辦公日曆表*.csv"))
    files = [f for f in files if "Google" not in f.name]
    if not files:
        raise SystemExit(f"No calendar CSVs in {IMPORT}")

    days = {}
    years = set()
    for path in files:
        rows = csv.reader(io.StringIO(read_text(path)))
        header = next(rows)
        if header[:3] != ["西元日期", "星期", "是否放假"]:
            raise SystemExit(f"{path.name}: unexpected header {header}")
        count = 0
        for row in rows:
            if not row or not row[0].strip():
                continue
            raw_date, _, flag = row[0].strip(), row[1], row[2].strip()
            name = row[3].strip() if len(row) > 3 else ""
            date = datetime.date(int(raw_date[:4]), int(raw_date[4:6]), int(raw_date[6:8]))
            off = flag == "2"
            weekend = date.weekday() >= 5
            years.add(date.year)
            count += 1
            if not name and off == weekend:
                continue
            entry = {"off": off}
            if name:
                entry["name"] = name
                if SHORT_NAMES.get(name):
                    entry["short"] = SHORT_NAMES[name]
            days[date.isoformat()] = entry
        print(f"{path.name}: {count} days")

    body = json.dumps(dict(sorted(days.items())), ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "// GENERATED by tools/build_holidays.py — do not edit by hand.\n"
        "// Taiwan's official office calendar (行政院人事行政總處), only the days a\n"
        "// Saturday/Sunday rule gets wrong or that carry a name. Years outside\n"
        "// TW_HOLIDAY_YEARS fall back to plain weekends (see Models.holidayOf).\n"
        f"const TW_HOLIDAY_YEARS = {json.dumps(sorted(years))};\n"
        f"const TW_HOLIDAYS = {body};\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(days)} days across {sorted(years)}")


if __name__ == "__main__":
    main()
