"""Regenerates app/js/ticker_directory.js from the exchange CSV exports.

Run from the project root:  python tools/build_ticker_directory.py

Inputs
  data/import/台灣所有上市公司.csv, 台灣所有上櫃公司.csv, 台灣所有興櫃公司.csv
      (MOPS company lists — only 公司代號 and 公司簡稱 are used; which file a
      code came from also becomes its listing venue, TICKER_BOARD_TW below)
  data/import/nasdaq.csv   (Nasdaq stock screener — only Symbol and Name)
  tools/curated_tickers.json   the hand-kept ETFs / popular names

The curated entries come first and win on a duplicate code, so the ETFs the
CSVs don't contain survive and popular names stay at the top of suggestions.
Everything else the app needs is derived here, so no personal or unrelated
column from the CSVs ever ships to the browser.
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMPORT = ROOT / "data" / "import"
OUT = ROOT / "app" / "js" / "ticker_directory.js"

# Order matters: if a code somehow shows up in more than one list, the first
# match wins (build_tw's found.setdefault/board.setdefault below).
TW_BOARD_FILES = [
    ("台灣所有上市公司.csv", "listed"),
    ("台灣所有上櫃公司.csv", "otc"),
    ("台灣所有興櫃公司.csv", "emerging"),
]

# Instruments almost nobody buys through a brokerage app: SPAC warrants and
# units, rights, preferred series, notes/debentures.
US_EXCLUDE_NAME = re.compile(
    r"\b(Warrants?|Units?|Rights?|Notes?|Debentures?|Preferred|Subordinated|Baby Bonds?)\b", re.I
)
# Descriptive tails Nasdaq appends to a company name.
US_NAME_TAIL = re.compile(
    r"\s*[-–]?\s*(?:Class\s+[A-Z]\s+|Series\s+[A-Z0-9]+\s+)?"
    r"(?:Common\s+Stock|Common\s+Shares?|Ordinary\s+Shares?|American\s+Depositary\s+Shares?|Depositary\s+Shares?"
    r"|Shares?\s+of\s+Beneficial\s+Interest|Capital\s+Stock)"
    r"(?:\s+Class\s+[A-Z])?(?:\s*\(.*?\))?\s*$",
    re.I,
)


def read_csv(path):
    with open(path, encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


# An ADR's tail can run on ("American Depositary Shares each representing six
# (6)"), so everything from that phrase onward is dropped.
US_ADS_TAIL = re.compile(
    r"\s+(?:(?:American\s+)?Depos[a-z]*\s+(?:Shares?|Shs|Receipts?)|(?:Common\s+Stock\s+)?ADR|ADS)\b.*$", re.I
)


def clean_us_name(name):
    name = US_ADS_TAIL.sub("", name.strip()).strip(" ,-–") or name.strip()
    while True:
        cleaned = US_NAME_TAIL.sub("", name).strip(" ,-–")
        if cleaned == name or not cleaned:
            return cleaned or name
        name = cleaned


def build_tw():
    found = {}
    board = {}
    for filename, tag in TW_BOARD_FILES:
        for row in read_csv(IMPORT / filename):
            code = row["公司代號"].strip()
            name = (row["公司簡稱"] or row["公司名稱"]).strip()
            if code and name:
                found.setdefault(code, name)
                board.setdefault(code, tag)
    return found, board


def build_us():
    found = {}
    for row in read_csv(IMPORT / "nasdaq.csv"):
        symbol = row["Symbol"].strip().upper()
        raw_name = row["Name"].strip()
        if not symbol or "^" in symbol or US_EXCLUDE_NAME.search(raw_name):
            continue
        symbol = symbol.replace("/", ".")  # BRK/B -> BRK.B, the form the app already uses
        found.setdefault(symbol, clean_us_name(raw_name))
    return found


def merge(curated, found):
    merged = [[c, n] for c, n in curated]
    seen = {c for c, _ in merged}
    for code in sorted(found):
        if code not in seen:
            merged.append([code, found[code]])
    return merged


def main():
    curated = json.loads((ROOT / "tools" / "curated_tickers.json").read_text(encoding="utf-8"))
    tw_names, tw_board = build_tw()
    data = {"TW": merge(curated["TW"], tw_names), "US": merge(curated["US"], build_us())}

    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    board_body = json.dumps(tw_board, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "// GENERATED by tools/build_ticker_directory.py — do not edit by hand.\n"
        "// Every free live source (TWSE OpenAPI, SEC EDGAR, Yahoo, NASDAQ) blocks direct\n"
        "// browser fetches with no CORS headers and this app has no backend, so the\n"
        "// exchange lists are baked in at build time. Curated ETFs/popular names come\n"
        "// first (suggestion order); a ticker not listed still types and saves fine.\n"
        f"const TICKER_DIRECTORY_RAW = {body};\n\n"
        "const TICKER_DIRECTORY = {\n"
        "  TW: TICKER_DIRECTORY_RAW.TW.map(([code, name]) => ({ code, name })),\n"
        "  US: TICKER_DIRECTORY_RAW.US.map(([code, name]) => ({ code, name })),\n"
        "};\n\n"
        "const TICKER_NAME_LOOKUP = {\n"
        "  TW: new Map(TICKER_DIRECTORY_RAW.TW),\n"
        "  US: new Map(TICKER_DIRECTORY_RAW.US),\n"
        "};\n\n"
        "// Company name for a market + ticker, or '' when it isn't in the directory.\n"
        "window.tickerName = (market, code) => (TICKER_NAME_LOOKUP[market] && TICKER_NAME_LOOKUP[market].get(code)) || '';\n"
        "window.TickerDirectory = TICKER_DIRECTORY;\n\n"
        "// A TW code's listing venue ('listed' 上市 | 'otc' 上櫃 | 'emerging' 興櫃),\n"
        "// from which of the three MOPS company lists it came from. A curated-only\n"
        "// code (an ETF like 0050, which MOPS doesn't list as a company) has none —\n"
        "// Models.twInvestmentCategory treats that, and 興櫃, as 上櫃 rather than\n"
        f"// dropping it from every tab.\nconst TICKER_BOARD_TW = {board_body};\n"
        "window.TickerBoard = TICKER_BOARD_TW;\n",
        encoding="utf-8",
    )
    print({k: len(v) for k, v in data.items()}, f"{OUT.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
